### ISSUE TITLE
Develop Project Timeline and Milestones

### ISSUE THREAD

**Issue by xKabbe** [xKabbe/star#5]
### Description

Create a detailed timeline with key milestones and deadlines to guide the project’s progress.

### Expected Actions

* [ ] Create initial project timeline
* [ ] Identify key milestones

### Definition Of Done

- [ ] Code implemented
- [ ] Tests implemented and passing
- [ ] Documentation implemented
- [ ] GitHub Actions are passing
